# Generated by Gemini 3.1 Pro
from __future__ import annotations

import os
from typing import Sequence

import diffrax
import equinox as eqx
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np

from src.constants import TrainingConstants
from src.model import XLR8


def solve_trajectory(model: XLR8, times: jax.Array, y0: jax.Array) -> jax.Array:
    term = diffrax.ODETerm(model)
    solver = diffrax.Tsit5()
    saveat = diffrax.SaveAt(ts=times)
    controller = diffrax.PIDController(
        rtol=TrainingConstants.RTOL,
        atol=TrainingConstants.ATOL,
    )

    sol = diffrax.diffeqsolve(
        terms=term,
        solver=solver,
        t0=times[0],
        t1=times[-1],
        dt0=times[1] - times[0],
        y0=y0,
        saveat=saveat,
        stepsize_controller=controller,
        max_steps=TrainingConstants.MAX_STEPS,
        throw=False,
    )
    return sol.ys


def plot_loss_curve(loss_history: Sequence[float], output_path: str) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    plt.figure(figsize=(8, 4))
    plt.plot(loss_history)
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("Training Loss")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()


def plot_rollouts(
    model: XLR8,
    raw_data: jax.Array,
    times: jax.Array,
    data_mean: jax.Array,
    data_std: jax.Array,
    output_path: str,
    num_to_plot: int = 5,
) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    mean = jnp.asarray(data_mean)
    std = jnp.asarray(data_std)

    # Plot a few trajectories: true in solid, predicted in dashed.
    indices = np.linspace(0, raw_data.shape[0] - 1, num_to_plot, dtype=int)

    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(projection="3d")

    for i, idx in enumerate(indices):
        true_traj = np.asarray(raw_data[idx])

        y0 = raw_data[idx, 0]
        y0_norm = (y0 - mean[0, 0]) / std[0, 0]

        pred_norm = solve_trajectory(model, times, y0_norm)
        pred = np.asarray(pred_norm * std[0, 0] + mean[0, 0])

        # Only label the first pair so legend doesn't duplicate entries
        true_label = "True Trajectory" if i == 0 else None
        pred_label = "Predicted Trajectory" if i == 0 else None

        ax.plot(
            true_traj[:, 0],
            true_traj[:, 1],
            true_traj[:, 2],
            alpha=0.7,
            label=true_label,
        )

        ax.plot(
            pred[:, 0],
            pred[:, 1],
            pred[:, 2],
            linestyle="--",
            linewidth=1.5,
            label=pred_label,
        )
    
    ax.set_title("True vs Predicted Lorenz Trajectories")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")
    ax.legend()
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
